// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWA2h1e7J8_SJGDgslYwcRlyTQIIjmiVA',
    appId: '1:15527930882:web:ae2909b5b1fffa5fcf0b1b',
    messagingSenderId: '15527930882',
    projectId: 'product-db-5f92a',
    authDomain: 'product-db-5f92a.firebaseapp.com',
    databaseURL: 'https://product-db-5f92a-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-5f92a.appspot.com',
    measurementId: 'G-WHGDMQH2RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh86ZYM4pnYe-9-cHy24ZEFGcWbn6ayZ8',
    appId: '1:15527930882:android:781a324c9db87ff0cf0b1b',
    messagingSenderId: '15527930882',
    projectId: 'product-db-5f92a',
    databaseURL: 'https://product-db-5f92a-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-5f92a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM8804f3Gn__TieG0YyB--ToTfqNJqQLI',
    appId: '1:15527930882:ios:a5f8a556edf8209fcf0b1b',
    messagingSenderId: '15527930882',
    projectId: 'product-db-5f92a',
    databaseURL: 'https://product-db-5f92a-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-5f92a.appspot.com',
    iosBundleId: 'com.example.productFebryan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM8804f3Gn__TieG0YyB--ToTfqNJqQLI',
    appId: '1:15527930882:ios:a5f8a556edf8209fcf0b1b',
    messagingSenderId: '15527930882',
    projectId: 'product-db-5f92a',
    databaseURL: 'https://product-db-5f92a-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-5f92a.appspot.com',
    iosBundleId: 'com.example.productFebryan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWA2h1e7J8_SJGDgslYwcRlyTQIIjmiVA',
    appId: '1:15527930882:web:440e76dc794b2b97cf0b1b',
    messagingSenderId: '15527930882',
    projectId: 'product-db-5f92a',
    authDomain: 'product-db-5f92a.firebaseapp.com',
    databaseURL: 'https://product-db-5f92a-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-5f92a.appspot.com',
    measurementId: 'G-HWY5B832KL',
  );
}
